name: Deploy server/ to Deta
on:
  push:
    paths: "server/**/*.py"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      - uses: MatyiFKBT/deta-deploy-action@v1.0.0
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN_OG1KJ676 }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: "main_micro" #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: "sheets-api" #Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project-dir: "server"
